[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-excel"
version = "1.4.6"
authors = [
    { name = "Yu Jeonghoon", email = "moning02004@naver.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "XlsxWriter>=3.0.0"
]

[project.urls]
"Homepage" = "https://github.com/moning02004/simple-excel"
"Bug Tracker" = "https://github.com/moning02004/simple-excel/issues"

[tool.setuptools.packages.find]
where = ["src"]